# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/hugolindfors/Documents/oru/dt501g/inlupp1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/hugolindfors/Documents/oru/dt501g/inlupp1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hugolindfors/Documents/oru/dt501g/inlupp1/CMakeFiles /Users/hugolindfors/Documents/oru/dt501g/inlupp1//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hugolindfors/Documents/oru/dt501g/inlupp1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named task_2

# Build rule for target.
task_2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 task_2
.PHONY : task_2

# fast build rule for target.
task_2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_2.dir/build.make CMakeFiles/task_2.dir/build
.PHONY : task_2/fast

#=============================================================================
# Target rules for targets named task_3

# Build rule for target.
task_3: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 task_3
.PHONY : task_3

# fast build rule for target.
task_3/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_3.dir/build.make CMakeFiles/task_3.dir/build
.PHONY : task_3/fast

#=============================================================================
# Target rules for targets named task_4

# Build rule for target.
task_4: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 task_4
.PHONY : task_4

# fast build rule for target.
task_4/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_4.dir/build.make CMakeFiles/task_4.dir/build
.PHONY : task_4/fast

#=============================================================================
# Target rules for targets named task_5

# Build rule for target.
task_5: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 task_5
.PHONY : task_5

# fast build rule for target.
task_5/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_5.dir/build.make CMakeFiles/task_5.dir/build
.PHONY : task_5/fast

#=============================================================================
# Target rules for targets named task_6

# Build rule for target.
task_6: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 task_6
.PHONY : task_6

# fast build rule for target.
task_6/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_6.dir/build.make CMakeFiles/task_6.dir/build
.PHONY : task_6/fast

#=============================================================================
# Target rules for targets named task_7

# Build rule for target.
task_7: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 task_7
.PHONY : task_7

# fast build rule for target.
task_7/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_7.dir/build.make CMakeFiles/task_7.dir/build
.PHONY : task_7/fast

#=============================================================================
# Target rules for targets named task_8

# Build rule for target.
task_8: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 task_8
.PHONY : task_8

# fast build rule for target.
task_8/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_8.dir/build.make CMakeFiles/task_8.dir/build
.PHONY : task_8/fast

#=============================================================================
# Target rules for targets named task_9

# Build rule for target.
task_9: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 task_9
.PHONY : task_9

# fast build rule for target.
task_9/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_9.dir/build.make CMakeFiles/task_9.dir/build
.PHONY : task_9/fast

#=============================================================================
# Target rules for targets named task_10

# Build rule for target.
task_10: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 task_10
.PHONY : task_10

# fast build rule for target.
task_10/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_10.dir/build.make CMakeFiles/task_10.dir/build
.PHONY : task_10/fast

#=============================================================================
# Target rules for targets named task_11

# Build rule for target.
task_11: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 task_11
.PHONY : task_11

# fast build rule for target.
task_11/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_11.dir/build.make CMakeFiles/task_11.dir/build
.PHONY : task_11/fast

task_10.o: task_10.c.o
.PHONY : task_10.o

# target to build an object file
task_10.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_10.dir/build.make CMakeFiles/task_10.dir/task_10.c.o
.PHONY : task_10.c.o

task_10.i: task_10.c.i
.PHONY : task_10.i

# target to preprocess a source file
task_10.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_10.dir/build.make CMakeFiles/task_10.dir/task_10.c.i
.PHONY : task_10.c.i

task_10.s: task_10.c.s
.PHONY : task_10.s

# target to generate assembly for a file
task_10.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_10.dir/build.make CMakeFiles/task_10.dir/task_10.c.s
.PHONY : task_10.c.s

task_11.o: task_11.c.o
.PHONY : task_11.o

# target to build an object file
task_11.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_11.dir/build.make CMakeFiles/task_11.dir/task_11.c.o
.PHONY : task_11.c.o

task_11.i: task_11.c.i
.PHONY : task_11.i

# target to preprocess a source file
task_11.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_11.dir/build.make CMakeFiles/task_11.dir/task_11.c.i
.PHONY : task_11.c.i

task_11.s: task_11.c.s
.PHONY : task_11.s

# target to generate assembly for a file
task_11.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_11.dir/build.make CMakeFiles/task_11.dir/task_11.c.s
.PHONY : task_11.c.s

task_2.o: task_2.c.o
.PHONY : task_2.o

# target to build an object file
task_2.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_2.dir/build.make CMakeFiles/task_2.dir/task_2.c.o
.PHONY : task_2.c.o

task_2.i: task_2.c.i
.PHONY : task_2.i

# target to preprocess a source file
task_2.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_2.dir/build.make CMakeFiles/task_2.dir/task_2.c.i
.PHONY : task_2.c.i

task_2.s: task_2.c.s
.PHONY : task_2.s

# target to generate assembly for a file
task_2.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_2.dir/build.make CMakeFiles/task_2.dir/task_2.c.s
.PHONY : task_2.c.s

task_3.o: task_3.c.o
.PHONY : task_3.o

# target to build an object file
task_3.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_3.dir/build.make CMakeFiles/task_3.dir/task_3.c.o
.PHONY : task_3.c.o

task_3.i: task_3.c.i
.PHONY : task_3.i

# target to preprocess a source file
task_3.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_3.dir/build.make CMakeFiles/task_3.dir/task_3.c.i
.PHONY : task_3.c.i

task_3.s: task_3.c.s
.PHONY : task_3.s

# target to generate assembly for a file
task_3.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_3.dir/build.make CMakeFiles/task_3.dir/task_3.c.s
.PHONY : task_3.c.s

task_4.o: task_4.c.o
.PHONY : task_4.o

# target to build an object file
task_4.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_4.dir/build.make CMakeFiles/task_4.dir/task_4.c.o
.PHONY : task_4.c.o

task_4.i: task_4.c.i
.PHONY : task_4.i

# target to preprocess a source file
task_4.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_4.dir/build.make CMakeFiles/task_4.dir/task_4.c.i
.PHONY : task_4.c.i

task_4.s: task_4.c.s
.PHONY : task_4.s

# target to generate assembly for a file
task_4.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_4.dir/build.make CMakeFiles/task_4.dir/task_4.c.s
.PHONY : task_4.c.s

task_5.o: task_5.c.o
.PHONY : task_5.o

# target to build an object file
task_5.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_5.dir/build.make CMakeFiles/task_5.dir/task_5.c.o
.PHONY : task_5.c.o

task_5.i: task_5.c.i
.PHONY : task_5.i

# target to preprocess a source file
task_5.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_5.dir/build.make CMakeFiles/task_5.dir/task_5.c.i
.PHONY : task_5.c.i

task_5.s: task_5.c.s
.PHONY : task_5.s

# target to generate assembly for a file
task_5.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_5.dir/build.make CMakeFiles/task_5.dir/task_5.c.s
.PHONY : task_5.c.s

task_6.o: task_6.c.o
.PHONY : task_6.o

# target to build an object file
task_6.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_6.dir/build.make CMakeFiles/task_6.dir/task_6.c.o
.PHONY : task_6.c.o

task_6.i: task_6.c.i
.PHONY : task_6.i

# target to preprocess a source file
task_6.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_6.dir/build.make CMakeFiles/task_6.dir/task_6.c.i
.PHONY : task_6.c.i

task_6.s: task_6.c.s
.PHONY : task_6.s

# target to generate assembly for a file
task_6.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_6.dir/build.make CMakeFiles/task_6.dir/task_6.c.s
.PHONY : task_6.c.s

task_7.o: task_7.c.o
.PHONY : task_7.o

# target to build an object file
task_7.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_7.dir/build.make CMakeFiles/task_7.dir/task_7.c.o
.PHONY : task_7.c.o

task_7.i: task_7.c.i
.PHONY : task_7.i

# target to preprocess a source file
task_7.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_7.dir/build.make CMakeFiles/task_7.dir/task_7.c.i
.PHONY : task_7.c.i

task_7.s: task_7.c.s
.PHONY : task_7.s

# target to generate assembly for a file
task_7.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_7.dir/build.make CMakeFiles/task_7.dir/task_7.c.s
.PHONY : task_7.c.s

task_8.o: task_8.c.o
.PHONY : task_8.o

# target to build an object file
task_8.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_8.dir/build.make CMakeFiles/task_8.dir/task_8.c.o
.PHONY : task_8.c.o

task_8.i: task_8.c.i
.PHONY : task_8.i

# target to preprocess a source file
task_8.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_8.dir/build.make CMakeFiles/task_8.dir/task_8.c.i
.PHONY : task_8.c.i

task_8.s: task_8.c.s
.PHONY : task_8.s

# target to generate assembly for a file
task_8.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_8.dir/build.make CMakeFiles/task_8.dir/task_8.c.s
.PHONY : task_8.c.s

task_9.o: task_9.c.o
.PHONY : task_9.o

# target to build an object file
task_9.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_9.dir/build.make CMakeFiles/task_9.dir/task_9.c.o
.PHONY : task_9.c.o

task_9.i: task_9.c.i
.PHONY : task_9.i

# target to preprocess a source file
task_9.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_9.dir/build.make CMakeFiles/task_9.dir/task_9.c.i
.PHONY : task_9.c.i

task_9.s: task_9.c.s
.PHONY : task_9.s

# target to generate assembly for a file
task_9.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/task_9.dir/build.make CMakeFiles/task_9.dir/task_9.c.s
.PHONY : task_9.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... task_10"
	@echo "... task_11"
	@echo "... task_2"
	@echo "... task_3"
	@echo "... task_4"
	@echo "... task_5"
	@echo "... task_6"
	@echo "... task_7"
	@echo "... task_8"
	@echo "... task_9"
	@echo "... task_10.o"
	@echo "... task_10.i"
	@echo "... task_10.s"
	@echo "... task_11.o"
	@echo "... task_11.i"
	@echo "... task_11.s"
	@echo "... task_2.o"
	@echo "... task_2.i"
	@echo "... task_2.s"
	@echo "... task_3.o"
	@echo "... task_3.i"
	@echo "... task_3.s"
	@echo "... task_4.o"
	@echo "... task_4.i"
	@echo "... task_4.s"
	@echo "... task_5.o"
	@echo "... task_5.i"
	@echo "... task_5.s"
	@echo "... task_6.o"
	@echo "... task_6.i"
	@echo "... task_6.s"
	@echo "... task_7.o"
	@echo "... task_7.i"
	@echo "... task_7.s"
	@echo "... task_8.o"
	@echo "... task_8.i"
	@echo "... task_8.s"
	@echo "... task_9.o"
	@echo "... task_9.i"
	@echo "... task_9.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

